CREATE DATABASE miBlog
DEFAULT CHARACTER  SET utf8;
USE miBlog;
CREATE TABLE usuarios (
  id int NOT NULL UNIQUE AUTO_INCREMENT,
  nombre VARCHAR(25) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  pass VARCHAR(255) NOT NULL,
  fecha_registro DATETIME NOT NULL,
  activo TINYINT NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE entradas (
  id int NOT NULL UNIQUE AUTO_INCREMENT,
  autor_id INT NOT NULL,
  titulo VARCHAR(255) NOT NULL UNIQUE,
  texto TEXT CHARACTER SET utf8 NOT NULL,
  fecha DATETIME NOT NULL,
  activa TINYINT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (autor_id) REFERENCES usuarios(id) ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE comentarios (
  id int NOT NULL UNIQUE AUTO_INCREMENT,
  autor_id INT NOT NULL,
  entrada_id INT NOT NULL,
  titulo VARCHAR(255) NOT NULL,
  texto TEXT CHARACTER SET utf8 NOT NULL,
  fecha DATETIME NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (autor_id) REFERENCES usuarios(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (entrada_id) REFERENCES entradas(id) ON UPDATE CASCADE ON DELETE RESTRICT
);